### ISSUE TITLE
Wan Atteck

### ISSUE THREAD

**Issue by 303103** [XploitWizer/XploitSPY#1]
Hey xploitwizer nice project  alternative l3mon rat  but one issue how to use wan Atteck and port forwarding Kali Linux please reply any solution love you

**Comment by RaoMK** [comment]
> Hey xploitwizer nice project alternative l3mon rat but one issue how to use wan Atteck and port forwarding Kali Linux please reply any solution love you

Thanks for supporting us but i would like to say please ask any kind of questions in our Telegram Group https://t.me/XploitWizer_Group it will be more easier for us to get connected with you guys.
Thanks
