### ISSUE TITLE
Automatic Offline

### ISSUE THREAD

**Issue by ckhackerz** [XploitWizer/XploitSPY#10]
After Second Time I Turn On Data It Connect & Work Perfectly But Within Some Sec It Goes Offline & Never Came Online Again. 

Tested On 2 Smartphone Oppo F9 Pro & Oppo F11 Running On Android 9 Both Connection Got Offline After Second Time Interenet Turn On.

**Comment by chrisstone07** [comment]
So your saying you turned off your internet connection on the mobile and when you turned it back on the bot does not reconnect?

**Comment by chrisstone07** [comment]
Please run a git pull and push it to heroku or your custom server to reflect the new changes. App now runs even when screen is locked and internet connection is toggled.

**Comment by ckhackerz** [comment]
Thanks XploitWizer/XploitSPY Working Awesome Now No Any Bugs But Plz Check
GPS Map Features Needs Some Improvement.
