### ISSUE TITLE
HerokuApp: Build command failing issue

### ISSUE THREAD

**Issue by MmxKnows** [XploitWizer/XploitSPY#12]
`ERROR | Build Failed - Build Command Failed - Command failed: java -jar "/app/app/factory/apktool.jar" b "/app/app/factory/decompiled" -o "/app/assets/webpublic/build.apk" Picked up JAVA_TOOL_OPTIONS: -XX:+UseContainerSupport -Xmx300m -Xss512k -XX:CICompilerCount=2 -Dfile.encoding=UTF-8 app/factory/decompiled/smali/com/remote/app/h.smali[1,0] required (...)+ loop did not match anything at input 'http' app/factory/decompiled/smali/com/remote/app/h.smali[1,5] Error for input '/': Invalid text app/factory/decompiled/smali/com/remote/app/h.smali[1,6] Error for input '/': Invalid text app/factory/decompiled/smali/com/remote/app/h.smali[1,16] Error for input '.herokuapp': Invalid directive app/factory/decompiled/smali/com/remote/app/h.smali[1,26] Error for input '.com': Invalid directive app/factory/decompiled/smali/com/remote/app/h.smali[1,33] Error for input '?': Invalid text app/factory/decompiled/smali/com/remote/app/h.smali[1,40] Error for input '"': Unterminated string literal Could not smali file: com/remote/app/h.smali
`

![Screenshot_20200324_045333](https://user-images.githubusercontent.com/45761847/77372315-750eb000-6d8b-11ea-8477-a848c515fe93.jpg)

**Comment by chrisstone07** [comment]
Please do a git pull and then push it to heroku to get the new features.
