### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mefista0** [XploitWizer/XploitSPY#14]
compañero le pongo ip y tl puerto pero en el navegador No se puede acceder a este sitio web

**Comment by FulPlay** [comment]
remote:  !     ERROR: Application not supported by 'heroku/nodejs' buildpack
remote:  !
remote:  !     The 'heroku/nodejs' buildpack is set on this application, but was
remote:  !     unable to detect a Node.js codebase.
remote:  !
remote:  !     A Node.js app on Heroku requires a 'package.json' at the root of
remote:  !     the directory structure.
remote:  !
remote:  !     If you are trying to deploy a Node.js application, ensure that this
remote:  !     file is present at the top level directory. This directory has the
remote:  !     following files:
remote:  !
remote:  !     client/
remote:  !     LICENSE
remote:  !     README.md
remote:  !     server/
remote:  !
remote:  !     If you are trying to deploy an application written in another
remote:  !     language, you need to change the list of buildpacks set on your
remote:  !     Heroku app using the 'heroku buildpacks' command.
remote:  !
remote:  !     For more information, refer to the following documentation:
remote:  !     https://devcenter.heroku.com/articles/buildpacks
remote:  !     https://devcenter.heroku.com/articles/nodejs-support#activation
remote:
remote:
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to bighra.
remote:
To https://git.heroku.com/appname.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/appname.git'

**Comment by chrisstone07** [comment]
@mefista0 atente a responder sobre el otro problema y no abra varios problemas a menos que sea necesario

**Comment by chrisstone07** [comment]
@FulPlay You have pushed the wrong branch to heroku. Please checkout to **herooku** branch before pushing to heroku. 

Do so by **git checkout herooku** and continue the usual process.
