### ISSUE TITLE
Facing issue with API http://authxspy.herokuapp.com/

### ISSUE THREAD

**Issue by chitranjan-morwal** [XploitWizer/XploitSPY#141]
Hello Team,

When I am trying to login into the webconsole it shows some errors:
FetchError: invalid json response body at http://authxspy.herokuapp.com/ reason: Unexpected token < in JSON at position 0
    at /home/user/XploitSPY/server/node_modules/node-fetch/lib/index.js:272:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/user/XploitSPY/server/includes/expressRoutes.js:80:26

After this I just checked the logs and try to debug this but I found this URL shows 404 not found means it is not able to take the response from there.
0|index    | response=== Response {
0|index    |   size: 0,
0|index    |   timeout: 0,
0|index    |   [Symbol(Body internals)]: {
0|index    |     body: PassThrough {
0|index    |       _readableState: [ReadableState],
0|index    |       _events: [Object: null prototype],
0|index    |       _eventsCount: 2,
0|index    |       _maxListeners: undefined,
0|index    |       _writableState: [WritableState],
0|index    |       allowHalfOpen: true,
0|index    |       [Symbol(kCapture)]: false,
0|index    |       [Symbol(kCallback)]: null
0|index    |     },
0|index    |     disturbed: false,
0|index    |     error: null
0|index    |   },
0|index    |   [Symbol(Response internals)]: {
0|index    |     url: 'http://authxspy.herokuapp.com/',
0|index    |     status: 404,
0|index    |     statusText: 'Not Found',
0|index    |     headers: Headers { [Symbol(map)]: [Object: null prototype] },
0|index    |     counter: 0
0|index    |   }
0|index    | }

Can anyone help me on this?

**Comment by chitranjan-morwal** [comment]
I have done some modifications in code so issue is resolved now thanks.

**Comment by daVinci13** [comment]
Same error:
`FetchError: invalid json response body at http://authxspy.herokuapp.com/ reason: Unexpected token < in JSON at position 0
    at /XploitSPY/server/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /XploitSPY/server/includes/expressRoutes.js:77:26
FetchError: invalid json response body at http://authxspy.herokuapp.com/ reason: Unexpected token < in JSON at position 0
    at /XploitSPY/server/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /XploitSPY/server/includes/expressRoutes.js:77:26`

**Comment by David-Hunt327** [comment]
@chitranjan-morwal What was the modification you made please, i made some modifications, before i could assses the dashboard but i realized i won't have a server anymore....Do you mind sharing your modification :).
