### ISSUE TITLE
No Devices Shown 

### ISSUE THREAD

**Issue by karniv0re-cyber** [XploitWizer/XploitSPY#16]
Even after installing the app into the victim's device and also allowed all permissions, still, the device is not shown in the device panel. I tried the same thing on multiple devices but no device was shown in the panel. Please Help.

**Comment by xd20111** [comment]
bro im facing same problem if you get any solution tell me also

**Comment by shriramrajarathinam** [comment]
Contact me https://t.me/shriramrajarathinam

**Comment by bapji** [comment]
For me working like butter 🤗

**Comment by chrisstone07** [comment]
@karniv0re-cyber and @xd20111 please mention which branch your using, master or herooku.

**Comment by shriramrajarathinam** [comment]
@chrisstone07 I'm using heroku

**Comment by Pawan83** [comment]
Device is not showing after installing APK victim device

**Comment by shriramrajarathinam** [comment]
> Device is not showing after installing APK victim device



> Device is not showing after installing APK victim device

Contact me https://t.me/shriramrajarathinam

**Comment by up2smoke** [comment]
> > Device is not showing after installing APK victim device
> 
> > Device is not showing after installing APK victim device
> 
> I tell you
> 
> Contact me https://t.me/shriramrajarathinam

Why u not Help Here, for all of the people?

**Comment by RaoMK** [comment]
issue fixed in new updates

**Comment by xd20111** [comment]
not brother I'm still facing same problem
