### ISSUE TITLE
Whats the diffrent between XploitSPY and the original L3MON?

### ISSUE THREAD

**Issue by up2smoke** [XploitWizer/XploitSPY#17]
With l3mon everythink works fine and without any Problems on my Raspberry Pi 3b+ with raspbianLite.

When Install XploitSPY (after a Clean Install from raspianLite) the Server works, but i cant build a APK and i dont know how to fix it

**Comment by chrisstone07** [comment]
What are errors you face while building? Please provide a detailed description.

**Comment by masif9899** [comment]
> What are errors you face while building? Please provide a detailed description.

Bro can you tell me how i can modify this source code.Becasue im new here and dont know how to change generated apk name package name and icon etc.
Please reply as early as possible..
Thank YOu.

**Comment by up2smoke** [comment]
I Install XploitSPY on a Raspbian 3B+ with a fresh Install of Raspbian Lite.
Step to Install:
`sudo apt update`
`sudo apt upgrade -y`

`curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -`
`sudo apt install nodejs git openjdk-11-jre-headles -y`
`sudo npm install pm2 -g`

`git clone https://github.com/XploitWizer/XploitSPY.git`
`cd ./XploitSPY/server`
`npm install`
`pm2 start index.js`

When i try to compile than the apk i got this error:

31/03/2020, 12:47:01 => ERROR | Build Failed - Build Command Failed - Command failed: java -jar "/home/pi/XploitSPY/server/app/factory/apktool.jar" b "/home/pi/XploitSPY/server/app/factory/decompiled" -o "/home/pi/XploitSPY/server/assets/webpublic/build.apk" S: WARNING: Could not write to (/home/pi/.local/share/apktool/framework), using /tmp instead... S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 2): [/tmp/brut_util_Jar_17642062992241383971.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 28, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /tmp/APKTOOL16593931036552730220.tmp, -0, arsc, -0, res/drawable-hdpi-v4/notification_bg_low_normal.9.png, -0, res/drawable-hdpi-v4/notification_bg_low_pressed.9.png, -0, res/drawable-hdpi-v4/notification_bg_normal.9.png, -0, res/drawable-hdpi-v4/notification_bg_normal_pressed.9.png, -0, png, -0, res/drawable-mdpi-v4/notification_bg_low_normal.9.png, -0, res/drawable-mdpi-v4/notification_bg_low_pressed.9.png, -0, res/drawable-mdpi-v4/notification_bg_normal.9.png, -0, res/drawable-mdpi-v4/notification_bg_normal_pressed.9.png, -0, res/drawable-xhdpi-v4/notification_bg_low_normal.9.png, -0, res/drawable-xhdpi-v4/notification_bg_low_pressed.9.png, -0, res/drawable-xhdpi-v4/notification_bg_normal.9.png, -0, res/drawable-xhdpi-v4/notification_bg_normal_pressed.9.png, -0, arsc, -I, /tmp/1.apk, -S, /home/pi/XploitSPY/server/app/factory/decompiled/res, -M, /home/pi/XploitSPY/server/app/factory/decompiled/AndroidManifest.xml] W: /tmp/brut_util_Jar_17642062992241383971.tmp: 17: /tmp/brut_util_Jar_17642062992241383971.tmp: Syntax error: "(" unexpected

**Comment by chrisstone07** [comment]
@masif9899 this a topic for another discussion so please wait until we release a tutorial on that.

**Comment by chrisstone07** [comment]
@up2smoke seems you've made some modifications to the AndroidManfiest file, please confirm if you have?

**Comment by up2smoke** [comment]
@chrisstone07 No, I haven't changed anything.  In the meantime I have also tried it with Java 9, & 10.  also the same.  then I reinstalled l3mon with Java 8 - no problems there

**Comment by chrisstone07** [comment]
@up2smoke if possible give me remote access so that I can see what's going wrong on the pi.

**Comment by RaoMK** [comment]
@up2smoke try updated codes now and make sure to have a look on updated commands in readme file before proceeding

**Comment by up2smoke** [comment]
@RaoMK thanks, i will test it in a few hours.
@chrisstone07, yes i can do it, If u Tell me how. My rPi runs headless without gui

**Comment by chrisstone07** [comment]
@up2smoke Ping me on my telegram handle (chrisstone07), I'll guide you as to how we can connect.

**Comment by up2smoke** [comment]
Still the Same 


`10/04/2020, 19:42:11 => ERROR | Build Failed - Build Command Failed - Command failed: java -jar "/home/pi/XploitSPY/server/app/factory/apktool.jar" b "/home/pi/XploitSPY/server/app/factory/decompiled" -o "/home/pi/XploitSPY/server/assets/webpublic/build.apk" S: WARNING: Could not write to (/root/.local/share/apktool/framework), using /tmp instead... S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable W: /tmp/brut_util_Jar_11856294940792195285.tmp: 17: /tmp/brut_util_Jar_11856294940792195285.tmp: Syntax error: "(" unexpected brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 2): [/tmp/brut_util_Jar_11856294940792195285.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 21, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /tmp/APKTOOL8239121706486562766.tmp, -0, resources.arsc, -0, META-INF/android.arch.lifecycle_runtime.version, -0, META-INF/androidx.core_core.version, -0, META-INF/androidx.versionedparcelable_versionedparcelable.version, -0, png, -0, arsc, -I, /tmp/1.apk, -S, /home/pi/XploitSPY/server/app/factory/decompiled/res, -M, /home/pi/XploitSPY/server/app/factory/decompiled/AndroidManifest.xml]`

**Comment by RaoMK** [comment]
@up2smoke please send a screen recording of your issue to our telegram group t.me/XploitWizer_Group

**Comment by chrisstone07** [comment]
@up2smoke this seems to be a platform specific issue, will release a version specific for the raspberry pi as apktool has issues on ARM when used with Java 11. Closing this for now.
