### ISSUE TITLE
Modify Application Permission 

### ISSUE THREAD

**Issue by shishir1337** [XploitWizer/XploitSPY#19]
Hello sir, 
You really did a good job.
I just want to request you that,
Can you please modify the application's Permission system ?
Like - When i will click the apk after install , it will show all the permission request pop up 
like other apps. for better understand i attached a screenshot .
![popup](https://user-images.githubusercontent.com/51515801/78066464-d13e8900-73b6-11ea-80bc-353124115bec.png)

**Comment by up2smoke** [comment]
U need to allow all of them

**Comment by shishir1337** [comment]
Yes sir i know... i just wanted to make the permission like that( runtime permission) ...
how can i edit the apk file ?

**Comment by bapji** [comment]
Use apk editer  and select apk file then  edit as common and change target  SDK version 22  and save file
![Screenshot_20200401-055838](https://user-images.githubusercontent.com/58431159/78087200-ef6baf80-73dd-11ea-90f9-2e2feafd7ec8.jpg)
![Screenshot_20200401-055850](https://user-images.githubusercontent.com/58431159/78087204-f4c8fa00-73dd-11ea-867a-381f6e86fbca.jpg)

**Comment by chrisstone07** [comment]
@shishir1337 use updated version from repo it already used runtime permissions.
