### ISSUE TITLE
Device data gets deleted (Using Heroku services)

### ISSUE THREAD

**Issue by julpari432** [XploitWizer/XploitSPY#24]
I have installed the app on heroku app. Every things working fine. But when I login after 1 hour all the device related data deleted and its log look like new. Why the data is not storing? I am using free heroku account. Is this the problem related to heroku services?
Help?

**Comment by chrisstone07** [comment]
Yes the free account works that way, either upgrade to heroku premium to have the server running 24/7 or use a VPS instead.
