### ISSUE TITLE
No repository field.

### ISSUE THREAD

**Issue by ndeso12** [XploitWizer/XploitSPY#26]
root@ndeso12:~/Downloads/XploitSPY/server# npm install

> bufferutil@4.0.1 install /home/ndeso12/Downloads/XploitSPY/server/node_modules/bufferutil
> node-gyp-build

> utf-8-validate@5.0.2 install /home/ndeso12/Downloads/XploitSPY/server/node_modules/utf-8-validate
> node-gyp-build

xploitspy@1.0.0 /home/ndeso12/Downloads/XploitSPY/server
├── bufferutil@4.0.1  extraneous
└── utf-8-validate@5.0.2  extraneous

npm WARN xploitspy@1.0.0 No repository field.
root@ndeso12:~/Downloads/XploitSPY/server# 

why?
help please.

**Comment by RaoMK** [comment]
we have updated commands and codes check and use them
