### ISSUE TITLE
server not opening 

### ISSUE THREAD

**Issue by sameerlike141** [XploitWizer/XploitSPY#27]
i setup on vps but when i put ip in browser noting opening not working on 80 port

**Comment by RaoMK** [comment]
@sameerlike141 make sure that no other service is running on port 80 and kindly use sudo on all commands if on linux server and if on windows server then use open with administration permissions

**Comment by RaoMK** [comment]
@sameerlike141 we hope your issue is resolved so i am clossing this issue here, if it's not solved you can re-open the issue again

**Comment by shazzrick** [comment]
I've tried using sudo still port is showing closed and IP doesn't bring up the site, i'm using an elastic IP for your reference.
