### ISSUE TITLE
Stuck at "Finalizing" when build apk.

### ISSUE THREAD

**Issue by riverstore** [XploitWizer/XploitSPY#29]
Hi, First I'd like to thanks for the great tool.

I'm setup XploitSPY on herokuapp, it's stuck with "Finalizing", I'm checking the log and see this

> 4/14/2020, 7:06:26 AM => SUCCESS | Build Succeded! 

Please help me.

Thanks a lot.

Regard.

**Comment by RaoMK** [comment]
If it stuck at Finalizing you need to edit your url from your browser search bar remove **builder** from it and put **dl** ther and it will download the apk for you
For Example: https://(IP or Domain).com/builder here remove builder and put dl as https://(IP or Domain).com/dl
it will download apk for you if it suck at finalizing without any error

**Comment by riverstore** [comment]
Thanks. I can download apk now.
