### ISSUE TITLE
Termux

### ISSUE THREAD

**Issue by pcdarin** [XploitWizer/XploitSPY#3]
Can this tool be run on Thermox? And I wish you had a training film from start to finish.

@sh4hu

**Comment by RaoMK** [comment]
> Can this tool be run on Thermox? And I wish you had a training film from start to finish.
> 
> @sh4hu

didn't test yet but will test and update the guide for termux basically its designed to host on a dedicated server with a static ip adresss

**Comment by Martin32222** [comment]
Hello I have a question about termux through which I run Kali Linux and when I entered the command I got an error like this. npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! errno UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! request to https://registry.npmjs.org/heroku failed, reason: unable to get local issuer certificate

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2020-03-30T11_55_10_260Z-debug.log
root@localhost:~# can I fix it or not
