### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by WrongProgram1** [XploitWizer/XploitSPY#30]
![Screenshot_2020_0415_062541](https://user-images.githubusercontent.com/49438078/79280088-10ee9000-7ee2-11ea-8257-84e01c56037b.png)

**Comment by WrongProgram1** [comment]
Here is mine https://wrong-program.herokuapp.com

**Comment by SiNaPsEr0x** [comment]
mine run correctly....

**Comment by WrongProgram1** [comment]
> mine run correctly....

How do I fix it?

**Comment by WrongProgram1** [comment]
Its working now😅 Maybe I just missed something (I created new app again)
