### ISSUE TITLE
I have a Question

### ISSUE THREAD

**Issue by WrongProgram1** [XploitWizer/XploitSPY#31]
Does the tool only have the permission to read? Or it can also write?

**Comment by RaoMK** [comment]
@WrongProgram1 currrently tool have only read permissisons

**Comment by chrisstone07** [comment]
@WrongProgram1 To read files? Yes presently only able to read and download files from the device. Will add write feature in future releases. Closing this issue for now.

**Comment by turjobd001** [comment]
Notification and SMS feature aren't working. Do anyone know how to fix this?
