### ISSUE TITLE
The devices gets removed from the list.

### ISSUE THREAD

**Issue by rajathv** [XploitWizer/XploitSPY#38]
The devices in the device list gets removed after a hour or so why is that? The device won't stay persistently connected to the server ? The app was still on mobile.

**Comment by RaoMK** [comment]
It's a limitation of Heroku Free plan not a issue of codes

**Comment by chrisstone07** [comment]
@rajathv Upgrade to heroku premium, the free plan restarts the server hence the data gets reset.
