### ISSUE TITLE
 Failed to connect to gihub.com 

### ISSUE THREAD

**Issue by sh4hu** [XploitWizer/XploitSPY#4]
root@kali:~#     git clone https://gihub.com/XploitWizer/XploitSPY.git
Cloning into 'XploitSPY'...
fatal: unable to access 'https://gihub.com/XploitWizer/XploitSPY.git/': Failed to connect to gihub.com port 443: Connection refused

**Comment by RaoMK** [comment]
> root@kali:~# git clone https://gihub.com/XploitWizer/XploitSPY.git
> Cloning into 'XploitSPY'...
> fatal: unable to access 'https://gihub.com/XploitWizer/XploitSPY.git/': Failed to connect to gihub.com port 443: Connection refused

sorry miss typed in in ReadME.md it's git clone https://github.com/XploitWizer/XploitSPY.git
