### ISSUE TITLE
Fatal : not a git repository

### ISSUE THREAD

**Issue by 4rjun9** [XploitWizer/XploitSPY#43]
#
![79632261-e881c280-817b-11ea-8b51-2c6c277eb474](https://user-images.githubusercontent.com/63835760/79645164-383baa80-81cb-11ea-8592-d6fa86e0dd64.jpg)

Someone please tell me how to clone repo.
I searched a lot but I could not find a solution.
Please give me a link from where I can know how to clone the repo.

**Comment by 4rjun9** [comment]
I do not know the command to clone repo

**Comment by 4rjun9** [comment]
I also searched on Git Hub but could not find a solution

**Comment by 4rjun9** [comment]
Please request you do not close the issue until my problem is resolved

**Comment by 4rjun9** [comment]
I'm noob i don't know how to clone repo

**Comment by heetu** [comment]
Please Refer This,
https://github.github.com/training-kit/downloads/github-git-cheat-sheet.pdf
