### ISSUE TITLE
fix readme install guide and create apk

### ISSUE THREAD

**Issue by SiNaPsEr0x** [XploitWizer/XploitSPY#46]
fix create apk bug blocked here
<img width="187" alt="image" src="https://user-images.githubusercontent.com/5438823/79742778-a5525b80-8303-11ea-8da1-c6aa3ba8484a.png">

fix without only video  on vps guide.. with old version

**Comment by RaoMK** [comment]
new video is updated and readme file have new guide for new updates don't follow old
