### ISSUE TITLE
Regarding Persistent

### ISSUE THREAD

**Issue by swagkarna** [XploitWizer/XploitSPY#51]
nowadays android phones use aggressive battery saving algorithm due to that  app will not run in background if the screen is locked and it will be killed automatically by task manager so that android payload wont be persistent . Whether your tool can bypass this

**Comment by RaoMK** [comment]
yup and solution is keeping a persistent notification there

**Comment by FrndZindagi** [comment]
> yup and solution is keeping a persistent notification there

Yup legend. But it could also be well solved by creating fake accessibility service for the payload
