### ISSUE TITLE
Heroku Banned my account

### ISSUE THREAD

**Issue by Abdulmanan0315** [XploitWizer/XploitSPY#55]
As the title says, 
i am looking for a free service where i can deploy this,
A tutorial might help

**Comment by creuZ** [comment]
Também estou com este problema! Já fiz várias contas e todas foram suspensas.

**Comment by creuZ** [comment]
> Como o título diz,
> estou procurando um serviço gratuito onde possa implantar isso.
> Um tutorial pode ajudar

Conseguiu resolver, cara?

**Comment by 10ke5h** [comment]
Same here my account got suspended too

**Comment by sauravroy9534** [comment]
same here my account got suspended too

**Comment by sauravroy9534** [comment]
What are u telling me?

**Comment by RaoMK** [comment]
Heroku Completely banned XploitSPY to deploy, so better to deploy on VPS
