### ISSUE TITLE
npm  install heroku 

### ISSUE THREAD

**Issue by whitehauler** [XploitWizer/XploitSPY#56]
when ever i run npm install heroku 
this will be the result 

npm WARN xploitspy@1.0.0 No repository field.

+ heroku@7.40.0
added 606 packages from 342 contributors and audited 10646 packages in 150.133s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

can someone please sort it out

**Comment by RaoMK** [comment]
its not any issue its showing that heroku cli is installed
