### ISSUE TITLE
Huge feature requests..

### ISSUE THREAD

**Issue by FrndZindagi** [XploitWizer/XploitSPY#57]
Dear XploitSPY

Thanks for bringing a revolutionary tool that's becoming a base for many advanced RAT and botnet. A similar tool that started with XploitSPY as base has now many advanced features (wow!). Sadly it's paid.

Since XploitSPY is the base CAN YOU PLEASE BRING SUCH FEATURES IN XPLOITSPY TOO ?!

TOOL : https://github.com/abhinavsuthar/Android_Spy_App

Thanks.

**Comment by turjobd001** [comment]
**SMS and Notification**
Those features aren't working, Please make a update. And lastly thanks for this amazing tool ❤

**Comment by 4445MB** [comment]
I don't know what to say but glitch.com also block my project.any help guys ?

**Comment by 4445MB** [comment]
No need ,I have true every step but looks like website Adims block links from github,thanks .
