### ISSUE TITLE
Got Error On APK Builder 

### ISSUE THREAD

**Issue by MuhammadAtif143** [XploitWizer/XploitSPY#6]
i am using nethunter kex on android i have latest java and node js why i got this [error]
![Untitled](https://user-images.githubusercontent.com/58996862/76144031-262ffd80-609e-11ea-9e3a-cbe6aa8a6d62.png)

**Comment by RaoMK** [comment]
well nethunter kex is not supported because the paths of android and linux are differnet 
try with root permissions maybe it will work
