### ISSUE TITLE
Herooku is suspending acc

### ISSUE THREAD

**Issue by vhigt** [XploitWizer/XploitSPY#63]
Herooku and glitch are suspending acc and i am unable to make it plz suggest any other branches

**Comment by r4jesh** [comment]
[](https://github.com/r4jesh/devillemon) use this

**Comment by rashid2547** [comment]
bed update

**Comment by RaoMK** [comment]
heroku and glitch are just server and if they are not allowing to host you its not an issue related to codes and we can't fix it
