### ISSUE TITLE
Hii

### ISSUE THREAD

**Issue by avipisal** [XploitWizer/XploitSPY#68]
$ pkg install python3
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python3 

Help me

**Comment by avipisal** [comment]
Hii

**Comment by avipisal** [comment]
$ pkg install python3
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python3

**Comment by heetu** [comment]
Try with python or python3.6
You are using pkg freeBDS so look once in FreeBDS Package Search Results .
