### ISSUE TITLE
Copyright Infingment - D3VL/L3MON

### ISSUE THREAD

**Issue by Jack-Rogers** [XploitWizer/XploitSPY#7]
Hey! 
We're delighted to see that you loved our release of L3MON so much that you're honoring us by copying the code and presenting it as your own!

https://github.com/D3VL/L3MON/

We Released L3MON under "The MIT License (MIT)"; 
It explicitly states `The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.` 
By editing the LICENCE to change the attribution name  (see below)
https://github.com/XploitWizer/XploitSPY/blob/bc58a442da0f0bcd173a40d29ddc181ebbbe3071/LICENSE#L3 
**You are infringing on our copyrighted property.**

Please could you revert the LICENCE.md to that of the original repositories
**AND** either; 
- Credit D3VL for the codebase in your readme.md file
- Delete this repository; Create a "Fork" of L3MON and edit that
- Or even better, help us develop L3MON, create a pull request

Please take action to rectify the above, **If compliance is not met we will take actions within our legal powers against yourselves for copyright infringement.**
We are happy to work with you to reach a satisfactory compromise. Though, please know; Copying code, and blatantly passing it off as your own is NOT ok.

**Comment by chrisstone07** [comment]
Sincere apologies @Jack-Rogers 

Initially when we cloned this repository locally we didn't plan on making it public and the changes in the LICENSE.md was a result of find and replace operation to avoid any build issues.

Changes have been made to reflect the original LICENSE file at L3MON and due credits have been added in the README file.

**Comment by Jack-Rogers** [comment]
Many thanks @chrisstone07 from all of us at D3VL, We worked very hard as a team to bring this out and was a little disappointed to see it being shown off as someone else's work.

We appreciate your compliance and wish you the best with continued development on this project 👍 it'll be interesting to see what new features you bring to the table!

I'll close this issue now 😎
